repositories:
  - name: java_app_example_clock
    url: git+https://bitbucket.org/automatitdevops/java_app_example_clock@helm_chart?ref=master

releases:
  - name: time-tracker
    namespace: time-tracker
    chart: java_app_example_clock/java_app_example_clock
    values:
    - nameOverride: TimeTracker
    - fullnameOverride: time-tracker
    - serviceAccount:
        create: false
    - image:
        repository: 315903692558.dkr.ecr.eu-central-1.amazonaws.com/denysm-test
        tag: "1.0"
    wait: true
