repositories:
  - name: java_app_example_clock
    url: git+https://bitbucket.org/automatitdevops/java_app_example_clock@helm_chart?ref=master

releases:
  - name: time-tracker
    namespace: time-tracker
    chart: java_app_example_clock/java_app_example_clock
    values:
    - nameOverride: TimeTracker
    - fullnameOverride: time-tracker
    - serviceAccount:
        create: false
    - image:
        repository: "REPOSITORY_URL"
        tag: "IMAG_TAG"
    wait: true
