name: Build Push

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
      
jobs:
  build_push:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    env:
      APP_REPO: java  # change this value to the repository with the Application
      AWS_ACCOUNT: 935818769908
      AWS_REGION: eu-central-1
    steps:
    #- name: Login to Docker Hub
    #  uses: docker/login-action@v2
    #  with:
    #    username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
    #    password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    # Configure AWS creds if Github secrets defined
    - name: Configure AWS creds with Github secrets
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ env.AWS_REGION }}

    # Configures AWS creds with OpenID Connect if no secrets defined
    #- name: Configure AWS creds with OpenID Connect
    #  uses: aws-actions/configure-aws-credentials@v1
    #  with:
    #    role-to-assume   : arn:aws:iam::123456789:role/my-github-actions   # First, create and configure role (e.g. my-github-actions), provide proper Account ID
    #    role-session-name: githubactions
    #    aws-region       : ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: actions/checkout@v3
    - name: Build the Docker image 
      if: "!contains(github.ref, 'pull')"
      run: docker build . --file Dockerfile --tag $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_REPO:$GITHUB_REF_NAME-$GITHUB_SHA

    - name: Build the Docker image on Pull request
      if: contains(github.ref, 'pull')
      run: docker build . --file Dockerfile --tag $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_REPO:$GITHUB_RUN_ID

    - name: Docker Push
      if: "!contains(github.ref, 'pull')"
      run: docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_REPO:$GITHUB_REF_NAME-$GITHUB_SHA
